# Generated by Django 6.0.6 on 2026-06-27 18:00

import common.timeutil
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorOverlimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationId', models.CharField(db_index=True, max_length=64)),
                ('amountKg', models.FloatField(default=0)),
                ('usedKg', models.FloatField(default=0)),
                ('category', models.CharField(blank=True, max_length=16, null=True)),
                ('staffCode', models.CharField(blank=True, max_length=64, null=True)),
                ('staffName', models.CharField(blank=True, max_length=200, null=True)),
                ('nodeId', models.CharField(blank=True, max_length=64, null=True)),
                ('createdAt', models.BigIntegerField(default=common.timeutil.now_ms)),
            ],
            options={
                'db_table': 'operator_overlimits',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='OperatorStationBalance',
            fields=[
                ('stationId', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('balanceKg', models.FloatField(default=0)),
                ('overlimitKg', models.FloatField(default=0)),
                ('updatedAt', models.BigIntegerField(default=common.timeutil.now_ms)),
            ],
            options={
                'db_table': 'operator_station_balances',
            },
        ),
    ]
