# Generated by Django 6.0.6 on 2026-07-12 19:54

import common.timeutil
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorShipment',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('fromStationId', models.CharField(db_index=True, max_length=64)),
                ('fromStationName', models.CharField(blank=True, default='', max_length=200)),
                ('toStationId', models.CharField(db_index=True, max_length=64)),
                ('toStationName', models.CharField(blank=True, default='', max_length=200)),
                ('amountKg', models.FloatField(default=0)),
                ('createdAt', models.BigIntegerField(default=common.timeutil.now_ms)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=16)),
                ('acceptedAt', models.BigIntegerField(blank=True, null=True)),
                ('acceptedKg', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operator_shipments',
                'ordering': ['-createdAt'],
            },
        ),
    ]
