# Generated by Django 6.0.6 on 2026-07-22 05:43

import common.timeutil
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_operatorshipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorCentralPurchase',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('amountKg', models.FloatField(default=0)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('createdAt', models.BigIntegerField(default=common.timeutil.now_ms)),
            ],
            options={
                'db_table': 'operator_central_purchases',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='OperatorCentralTank',
            fields=[
                ('id', models.CharField(default='main', max_length=32, primary_key=True, serialize=False)),
                ('balanceKg', models.FloatField(default=0)),
                ('totalPurchasedKg', models.FloatField(default=0)),
                ('updatedAt', models.BigIntegerField(default=common.timeutil.now_ms)),
            ],
            options={
                'db_table': 'operator_central_tank',
            },
        ),
    ]
