# Generated by Django 6.0.6 on 2026-08-06 09:48

import common.timeutil
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_operatorcentralpurchase_operatorcentraltank'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorShipmentRequest',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('fromStationId', models.CharField(db_index=True, max_length=64)),
                ('fromStationName', models.CharField(blank=True, default='', max_length=200)),
                ('toStationId', models.CharField(db_index=True, max_length=64)),
                ('toStationName', models.CharField(blank=True, default='', max_length=200)),
                ('amountKg', models.FloatField(default=0)),
                ('masulShaxs', models.CharField(blank=True, default='', max_length=200)),
                ('requestedByCode', models.CharField(blank=True, default='', max_length=64)),
                ('requestedByName', models.CharField(blank=True, default='', max_length=200)),
                ('createdAt', models.BigIntegerField(default=common.timeutil.now_ms)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=16)),
                ('decidedAt', models.BigIntegerField(blank=True, null=True)),
                ('decidedByCode', models.CharField(blank=True, default='', max_length=64)),
                ('decidedByName', models.CharField(blank=True, default='', max_length=200)),
                ('rejectReason', models.CharField(blank=True, default='', max_length=300)),
                ('shipmentId', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'operator_shipment_requests',
                'ordering': ['-createdAt'],
            },
        ),
    ]
