# Generated by Django 6.0.6 on 2026-08-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0004_operatorshipmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorshipmentrequest',
            name='allowedKg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operatorshipmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('allowed', 'allowed'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=16),
        ),
    ]
