# Generated by Django 6.0.6 on 2026-06-26 05:11

import common.timeutil
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('worker', 'worker'), ('admin', 'admin'), ('developer', 'developer')], default='admin', max_length=16)),
                ('displayName', models.CharField(blank=True, default='', max_length=200)),
                ('nodeId', models.CharField(blank=True, max_length=64, null=True)),
                ('stationId', models.CharField(blank=True, max_length=64, null=True)),
                ('codeType', models.CharField(choices=[('admin', 'admin'), ('developer', 'developer')], default='admin', max_length=16)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.BigIntegerField(default=common.timeutil.now_ms)),
                ('updatedAt', models.BigIntegerField(default=common.timeutil.now_ms)),
            ],
            options={
                'db_table': 'access_codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('uid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('role', models.CharField(choices=[('worker', 'worker'), ('admin', 'admin'), ('developer', 'developer')], default='worker', max_length=16)),
                ('stationId', models.CharField(blank=True, max_length=64, null=True)),
                ('nodeId', models.CharField(blank=True, max_length=64, null=True)),
                ('displayName', models.CharField(blank=True, max_length=200, null=True)),
                ('staffVaultFullName', models.CharField(blank=True, max_length=200, null=True)),
                ('createdAt', models.BigIntegerField(default=common.timeutil.now_ms)),
                ('lastSeen', models.BigIntegerField(default=common.timeutil.now_ms)),
            ],
            options={
                'db_table': 'active_sessions',
                'ordering': ['-lastSeen'],
            },
        ),
        migrations.CreateModel(
            name='BlockedCode',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('blockedAt', models.BigIntegerField(default=common.timeutil.now_ms)),
                ('blockedByDisplayName', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'blocked_codes',
                'ordering': ['-blockedAt'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLock',
            fields=[
                ('deviceId', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('attempts', models.IntegerField(default=0)),
                ('lockedAt', models.BigIntegerField(default=common.timeutil.now_ms)),
                ('lockedCode', models.CharField(blank=True, default='', max_length=64)),
                ('isBlocked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'device_locks',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('wrong_code', 'wrong_code'), ('device_locked', 'device_locked'), ('successful_login', 'successful_login')], max_length=32)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('deviceId', models.CharField(blank=True, default='', max_length=128)),
                ('timestamp', models.BigIntegerField(default=common.timeutil.now_ms)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'security_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erju', models.CharField(blank=True, default='', max_length=120)),
                ('zapravka', models.CharField(blank=True, default='', max_length=120)),
                ('tabelNumber', models.CharField(db_index=True, max_length=64)),
                ('fullName', models.CharField(blank=True, default='', max_length=200)),
                ('role', models.CharField(blank=True, choices=[('worker', 'worker'), ('operator', 'operator')], max_length=16, null=True)),
                ('stationId', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'staff',
                'ordering': ['tabelNumber'],
            },
        ),
    ]
