# Generated by Django 6.0.6 on 2026-08-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='allowedSections',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
