# Generated by Django 6.0.6 on 2026-08-15 11:03

import common.timeutil
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accesscode_allowedsections'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceTemplate',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('vectors', models.TextField(blank=True, default='')),
                ('samples', models.TextField(blank=True, default='')),
                ('sampleCount', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('createdAt', models.BigIntegerField(default=common.timeutil.now_ms)),
                ('updatedAt', models.BigIntegerField(default=common.timeutil.now_ms)),
                ('createdByDisplayName', models.CharField(blank=True, default='', max_length=200)),
                ('lastMatchedAt', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'face_templates',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='photoUpdatedAt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
