# Generated by Django 6.0.6 on 2026-07-16 11:37

import common.timeutil
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KorxonaWorkerCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffCode', models.CharField(db_index=True, max_length=64)),
                ('korxonaNomi', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=32)),
                ('updatedAt', models.BigIntegerField(default=common.timeutil.now_ms)),
            ],
            options={
                'db_table': 'korxona_worker_codes',
                'ordering': ['korxonaNomi'],
                'unique_together': {('staffCode', 'korxonaNomi')},
            },
        ),
    ]
