# Generated by Django 6.0.6 on 2026-08-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_korxonaworkercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='depo',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
