# Generated by Django 6.0.6 on 2026-08-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_depo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelrecord',
            index=models.Index(fields=['locCode', 'date'], name='fuel_record_locCode_22b872_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelrecord',
            index=models.Index(fields=['date'], name='fuel_record_date_a7b873_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['stationId', '-timestamp'], name='submissions_station_2f0bbf_idx'),
        ),
    ]
