# Generated by Django 6.0.6 on 2026-06-26 05:11

import common.timeutil
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('userName', models.CharField(blank=True, default='', max_length=200)),
                ('userRole', models.CharField(blank=True, default='', max_length=16)),
                ('action', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete')], max_length=16)),
                ('entityType', models.CharField(db_index=True, max_length=64)),
                ('entityId', models.CharField(blank=True, default='', max_length=160)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.BigIntegerField(db_index=True, default=common.timeutil.now_ms)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
