# Generated by Django 6.0.6 on 2026-06-26 05:11

import common.timeutil
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('createdAt', models.BigIntegerField(default=common.timeutil.now_ms)),
                ('updatedAt', models.BigIntegerField(default=common.timeutil.now_ms)),
            ],
            options={
                'db_table': 'approvals',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='ClosedDay',
            fields=[
                ('docId', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updatedAt', models.BigIntegerField(default=common.timeutil.now_ms)),
            ],
            options={
                'db_table': 'closed_days',
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('korxona', 'korxona'), ('qurulish', 'qurulish'), ('lokomotiv', 'lokomotiv'), ('stansiya', 'stansiya')], max_length=16)),
                ('korxonaNomi', models.CharField(blank=True, max_length=200, null=True)),
                ('seriya', models.CharField(blank=True, max_length=64, null=True)),
                ('lokomotivNumber', models.CharField(blank=True, max_length=64, null=True)),
                ('stansiyaName', models.CharField(blank=True, max_length=200, null=True)),
                ('stationId', models.CharField(db_index=True, max_length=64)),
                ('limit', models.FloatField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.CharField(blank=True, default='', max_length=120)),
                ('createdAt', models.BigIntegerField(default=common.timeutil.now_ms)),
                ('updatedAt', models.BigIntegerField(default=common.timeutil.now_ms)),
            ],
            options={
                'db_table': 'limits',
                'ordering': ['-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=16)),
                ('stationId', models.CharField(blank=True, default='', max_length=64)),
                ('order', models.IntegerField(default=0)),
                ('label', models.CharField(max_length=200)),
                ('fieldKey', models.CharField(max_length=64)),
                ('fieldType', models.CharField(max_length=16)),
                ('options', models.JSONField(blank=True, null=True)),
                ('isRequired', models.BooleanField(default=False)),
                ('isVisible', models.BooleanField(default=True)),
                ('showWhen', models.JSONField(blank=True, null=True)),
                ('pdfColumn', models.CharField(blank=True, max_length=120, null=True)),
                ('createdAt', models.BigIntegerField(default=common.timeutil.now_ms)),
                ('updatedAt', models.BigIntegerField(default=common.timeutil.now_ms)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updatedAt', models.BigIntegerField(default=common.timeutil.now_ms)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Uzel',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'uzellar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('stationId', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updatedAt', models.BigIntegerField(default=common.timeutil.now_ms)),
            ],
            options={
                'db_table': 'variants',
            },
        ),
        migrations.CreateModel(
            name='Zapravka',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('uzelId', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'zapravkalar',
                'ordering': ['uzelId', 'id'],
            },
        ),
    ]
